export interface SeedResort {
  slug: string;
  name: string;
  region_slug: string;
  lat: number;
  lng: number;
  elevation_ft: number;
  trail_count: number;
  website: string;
  summary: string;
}

export const FLAGSHIP_RESORTS: SeedResort[] = [
  {
    slug: "vail",
    name: "Vail",
    region_slug: "us-co",
    lat: 39.6403,
    lng: -106.3742,
    elevation_ft: 11570,
    trail_count: 195,
    website: "https://www.vail.com",
    summary: "One of the largest ski resorts in North America, Vail spans seven legendary back bowls and groomed front-side terrain across 5,317 acres.",
  },
  {
    slug: "aspen-snowmass",
    name: "Aspen Snowmass",
    region_slug: "us-co",
    lat: 39.2084,
    lng: -106.949,
    elevation_ft: 12510,
    trail_count: 336,
    website: "https://www.aspensnowmass.com",
    summary: "Four mountains in one destination — Aspen Mountain, Snowmass, Aspen Highlands, and Buttermilk — offering diverse terrain for every ability level.",
  },
  {
    slug: "breckenridge",
    name: "Breckenridge",
    region_slug: "us-co",
    lat: 39.4817,
    lng: -106.0384,
    elevation_ft: 12998,
    trail_count: 187,
    website: "https://www.breckenridge.com",
    summary: "Historic mining-town charm meets high-alpine skiing with five peaks, above-treeline bowls, and family-friendly groomers.",
  },
  {
    slug: "telluride",
    name: "Telluride",
    region_slug: "us-co",
    lat: 37.9375,
    lng: -107.8123,
    elevation_ft: 13150,
    trail_count: 148,
    website: "https://www.telluride.com",
    summary: "Remote box canyon resort known for steep chutes, uncrowded slopes, and stunning San Juan Mountain scenery.",
  },
  {
    slug: "park-city",
    name: "Park City",
    region_slug: "us-ut",
    lat: 40.6514,
    lng: -111.508,
    elevation_ft: 10026,
    trail_count: 330,
    website: "https://www.parkcitymountain.com",
    summary: "The largest ski resort in the United States by acreage, minutes from Salt Lake City with extensive terrain for all levels.",
  },
  {
    slug: "snowbird",
    name: "Snowbird",
    region_slug: "us-ut",
    lat: 40.583,
    lng: -111.653,
    elevation_ft: 11000,
    trail_count: 169,
    website: "https://www.snowbird.com",
    summary: "Legendary Utah powder destination with steep chutes, deep snow, and a tram to 11,000 feet.",
  },
  {
    slug: "alta",
    name: "Alta",
    region_slug: "us-ut",
    lat: 40.5884,
    lng: -111.6386,
    elevation_ft: 10550,
    trail_count: 116,
    website: "https://www.alta.com",
    summary: "Skier-only classic with some of the deepest snow in North America and old-school, no-frills mountain culture.",
  },
  {
    slug: "jackson-hole",
    name: "Jackson Hole",
    region_slug: "us-wy",
    lat: 43.5875,
    lng: -110.8279,
    elevation_ft: 10450,
    trail_count: 133,
    website: "https://www.jacksonhole.com",
    summary: "Expert paradise in the Tetons, famous for Corbet's Couloir and consistent cold-smoke powder.",
  },
  {
    slug: "mammoth-mountain",
    name: "Mammoth Mountain",
    region_slug: "us-ca",
    lat: 37.6308,
    lng: -119.0326,
    elevation_ft: 11053,
    trail_count: 175,
    website: "https://www.mammothmountain.com",
    summary: "California's largest ski area with long seasons, sunny days, and expansive high-alpine terrain.",
  },
  {
    slug: "palisades-tahoe",
    name: "Palisades Tahoe",
    region_slug: "us-ca",
    lat: 39.1969,
    lng: -120.2358,
    elevation_ft: 9050,
    trail_count: 170,
    website: "https://www.palisadestahoe.com",
    summary: "Formerly Squaw Valley, Olympic legacy resort with steep KT-22 lines and Lake Tahoe views.",
  },
  {
    slug: "killington",
    name: "Killington",
    region_slug: "us-vt",
    lat: 43.6045,
    lng: -72.8201,
    elevation_ft: 4241,
    trail_count: 155,
    website: "https://www.killington.com",
    summary: "The Beast of the East — Vermont's largest ski area with the longest season in the eastern United States.",
  },
  {
    slug: "stowe",
    name: "Stowe",
    region_slug: "us-vt",
    lat: 44.5303,
    lng: -72.7814,
    elevation_ft: 4850,
    trail_count: 116,
    website: "https://www.stowe.com",
    summary: "Classic New England resort beneath Mount Mansfield with charming village atmosphere and varied terrain.",
  },
  {
    slug: "sun-valley",
    name: "Sun Valley",
    region_slug: "us-id",
    lat: 43.6807,
    lng: -114.3626,
    elevation_ft: 9150,
    trail_count: 121,
    website: "https://www.sunvalley.com",
    summary: "America's first destination ski resort, known for impeccable grooming, sunny weather, and celebrity history.",
  },
  {
    slug: "whistler-blackcomb",
    name: "Whistler Blackcomb",
    region_slug: "ca-bc",
    lat: 50.1163,
    lng: -122.9574,
    elevation_ft: 7494,
    trail_count: 200,
    website: "https://www.whistlerblackcomb.com",
    summary: "North America's largest ski resort by acreage, with two connected mountains and a vibrant pedestrian village.",
  },
  {
    slug: "lake-louise",
    name: "Lake Louise",
    region_slug: "ca-ab",
    lat: 51.4254,
    lng: -116.1773,
    elevation_ft: 8650,
    trail_count: 164,
    website: "https://www.skilouise.com",
    summary: "Banff National Park gem with turquoise lake views, wide open bowls, and reliable Rocky Mountain snow.",
  },
  {
    slug: "sunshine-village",
    name: "Sunshine Village",
    region_slug: "ca-ab",
    lat: 51.0784,
    lng: -115.782,
    elevation_ft: 8954,
    trail_count: 137,
    website: "https://www.skibanff.com",
    summary: "High-elevation Banff resort with Canada's longest non-glacial season and the Delirium Dive expert zone.",
  },
  {
    slug: "mont-tremblant",
    name: "Mont Tremblant",
    region_slug: "ca-qc",
    lat: 46.2127,
    lng: -74.5844,
    elevation_ft: 2871,
    trail_count: 102,
    website: "https://www.tremblant.ca",
    summary: "Québec's premier ski destination with European-style village, night skiing, and family-friendly slopes.",
  },
  {
    slug: "big-sky",
    name: "Big Sky",
    region_slug: "us-mt",
    lat: 45.2618,
    lng: -111.4013,
    elevation_ft: 11166,
    trail_count: 300,
    website: "https://www.bigskyresort.com",
    summary: "Biggest skiing in America by vertical drop, with Lone Peak Tram access to expert terrain and minimal crowds.",
  },
  {
    slug: "taos",
    name: "Taos Ski Valley",
    region_slug: "us-nm",
    lat: 36.5956,
    lng: -105.4485,
    elevation_ft: 12481,
    trail_count: 110,
    website: "https://www.skitaos.com",
    summary: "Authentic New Mexico ski culture with steep, rocky chutes and some of the Southwest's best powder.",
  },
  {
    slug: "dear-valley",
    name: "Deer Valley",
    region_slug: "us-ut",
    lat: 40.6375,
    lng: -111.4783,
    elevation_ft: 9570,
    trail_count: 103,
    website: "https://www.deervalley.com",
    summary: "Upscale, skier-only resort famous for impeccable grooming, limited ticket sales, and luxury amenities.",
  },
];

export interface SeedProduct {
  slug: string;
  category: string;
  brand: string;
  name: string;
  description: string;
}

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    slug: "rossignol-hero-elite-st",
    category: "skis",
    brand: "Rossignol",
    name: "Hero Elite ST",
    description: "Frontside carving ski with race-inspired construction for precise turns on hardpack.",
  },
  {
    slug: "salomon-qst-blank",
    category: "skis",
    brand: "Salomon",
    name: "QST Blank",
    description: "Big-mountain freeride ski built for powder, steeps, and variable backcountry conditions.",
  },
  {
    slug: "atomic-hawx-ultra-130",
    category: "boots",
    brand: "Atomic",
    name: "Hawx Ultra 130",
    description: "Lightweight performance boot with customizable fit for aggressive all-mountain skiing.",
  },
  {
    slug: "lange-lx-110",
    category: "boots",
    brand: "Lange",
    name: "LX 110 HV",
    description: "High-volume fit boot designed for comfort and control on groomed runs.",
  },
  {
    slug: "marker-griffon-13",
    category: "bindings",
    brand: "Marker",
    name: "Griffon 13 ID",
    description: "Versatile alpine binding with reliable release and easy step-in for all-mountain use.",
  },
  {
    slug: "look-pivot-15",
    category: "bindings",
    brand: "Look",
    name: "Pivot 15 GW",
    description: "Legendary freeride binding with turntable heel piece for strong retention and smooth release.",
  },
  {
    slug: "smith-vantage-helmet",
    category: "helmets",
    brand: "Smith",
    name: "Vantage MIPS",
    description: "Premium helmet with MIPS protection, adjustable ventilation, and audio-compatible ear pads.",
  },
  {
    slug: "giro-luxe-goggles",
    category: "goggles",
    brand: "Giro",
    name: "Luxe",
    description: "OTG-compatible goggle with Vivid lens technology for enhanced contrast in flat light.",
  },
];
